[package]
name = "vv-gui"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
eframe.workspace = true
rfd.workspace = true
time.workspace = true
toml_edit = "0.23.7"
toml_parser = "1.0.4"
tracing.workspace = true
tracing-subscriber.workspace = true
