[package]
name = "vv-gui"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
eframe.workspace = true
toml_edit = "0.23.7"
tracing.workspace = true
tracing-subscriber.workspace = true
